import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
 await page.goto('https://mephar-sit.acdtech.asia/auth/sign-in/');
 await page.getByRole('textbox', { name: 'Tên đăng nhập' }).click();
 await page.getByRole('textbox', { name: 'Tên đăng nhập' }).fill('test30');
 await page.getByRole('textbox', { name: 'Tên đăng nhập' }).press('Tab');
 await page.getByRole('textbox', { name: 'Mật khẩu' }).fill('12345678');
 await page.getByRole('button', { name: 'Đăng nhập' }).click();
 await page.getByRole('menuitem', { name: 'Sản phẩm' }).click();
 await page.getByRole('menuitem', { name: 'Danh sách sản phẩm' }).click();
 await page.getByRole('cell', { name: 'HH00002' }).click();
 await page.getByRole('button', { name: 'Thêm mới' }).click();
 await page.getByText('Thêm mới hàng hóa').click();
 await page.getByRole('textbox', { name: 'Mã hàng tự động' }).click();
 await page.getByRole('textbox', { name: 'Mã hàng tự động' }).fill('HH00002');
 await page.getByRole('textbox', { name: 'Mã vạch tự động' }).click();
 await page.getByRole('textbox', { name: 'Mã vạch tự động' }).fill('HH00002');
 await page.getByRole('textbox', { name: 'Nhập tên hàng hóa' }).click();
 await page.getByRole('textbox', { name: 'Nhập tên hàng hóa' }).fill('Thuốc đau lưng');
 await page.locator('#rc_select_28').click();
 await page.getByRole('textbox', { name: 'Nhập giá bán' }).click();
 await page.getByRole('textbox', { name: 'Nhập giá bán' }).fill('2000');
 await page.getByRole('textbox', { name: 'Tồn kho' }).click();
 await page.getByRole('textbox', { name: 'Tồn kho' }).fill('1234');
 await page.getByRole('textbox', { name: 'Nhập đơn vị cơ bản' }).click();
 await page.getByRole('textbox', { name: 'Nhập đơn vị cơ bản' }).fill('vỉ');
 await page.getByRole('button', { name: 'Lưu', exact: true }).click();await page.goto('https://mephar-sit.acdtech.asia/');
 await expect(page.locator('body')).toContainText('Mã hàng HH00002 đã tồn tại.');
 await page.goto('https://mephar-sit.acdtech.asia/auth/sign-in/');
 await page.getByRole('textbox', { name: 'Tên đăng nhập' }).click();
 await page.getByRole('textbox', { name: 'Tên đăng nhập' }).fill('test30');
 await page.getByRole('textbox', { name: 'Tên đăng nhập' }).press('Tab');
 await page.getByRole('textbox', { name: 'Mật khẩu' }).fill('12345678');
 await page.getByRole('button', { name: 'Đăng nhập' }).click();
 await page.getByText('Sản phẩm').click();
 await page.getByText('Danh sách sản phẩm').click();
 await page.getByRole('button', { name: 'Thêm mới' }).click();
 await page.getByText('Thêm mới hàng hóa').click();
 await page.getByRole('button', { name: 'Tải ảnh lên hoặc kéo và thả' }).click();
 await page.getByRole('button', { name: 'Tải ảnh lên hoặc kéo và thả' }).setInputFiles('anh2.jfif');
 await expect(page.locator('div').filter({ hasText: /^anh2\.jfif$/ }).nth(2)).toBeVisible();
});